services:
  app:
    build: .
    container_name: credit-app
    ports:
      - "8501:8501"
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./src:/app/src
      - ./api:/app/api
      - ./app:/app/app
    restart: always
    command: >
      bash -c "uvicorn api.main:app --host 0.0.0.0 --port 8000 &
               streamlit run app/app.py --server.port 8501 --server.address 0.0.0.0"
